### ISSUE TITLE
Write gbif_download() function

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#1]
Usage:

```R
gbif_download(
    taxa="https://raw.githubusercontent.com/trias-project/alien-plants-belgium/afbd2805de77afd79fb74669c403d40f1416661b/data/processed/taxon.csv",
    country="BE", # default
    output="../data/output/gbif_downloads.csv" # default
)
```

The script would:

1. Verify and report errors the parameter `checklist`:
    * Can it be found
    * Is it a csv file
    * Is it a GitHub commit URL
    * Has the file a column `gbif_nubKey`
    * Does `gbif_nubKey` contain numbers only
2. Verify and report errors for the option `country`:
    * Is it a valid ISO 3166-1 alpha-2
3. Verify and report errors for the option `output`:
    * Does the file exist
3. Use rgbif to [trigger a download](https://github.com/ropensci/rgbif/blob/master/vignettes/downloads.Rmd)
4. Write information to `data/output/gbif_downloads.csv`:
    * `gbif_download_key`: GBIF download UUID
    * `input_checklist`: checklist (parameter)
    * `input_country`: country (parameter)

**Comment by peterdesmet** [comment]
Note: function should be part of TrIAS R package, not this repository.

**Comment by damianooldoni** [comment]
point 1,2,3 not present anymore in the pipeline. But I the checks have been written and I think they are still very useful while merging checklists.

**Comment by peterdesmet** [comment]
Rather than a function, we opted to use basic R and rgbif functionality: https://github.com/trias-project/pipeline/blob/master/src/occurrences.Rmd. Closing issue.
