### ISSUE TITLE
GBIF match for modelling species

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#14]
Notes regarding GBIF match for modelling species:

- [x] `Podarcis sicula` (https://www.gbif.org/species/2469233) considered synonym of `Podarcis siculus`. I propose to update our spelling to `Podarcis siculus`. OK?
- [x] `Persicaria wallichii` (https://www.gbif.org/species/6391908) considered synonym of `Koenigia polystachya` (https://www.gbif.org/species/8848208) which has a whole number of synonyms (see on the left). Do we keep our restricted `Persicaria wallichii` taxon concept or widen to `Koenigia polystachya`?
- [x] `Aspius aspius` (https://www.gbif.org/species/2360181) considered synonym of `Leuciscus aspius` (https://www.gbif.org/species/5851603) with a number of synonyms. Keep restricted or widen?
- [x] `Astacus leptodactylus` (https://www.gbif.org/species/4417551) considered synonym of `Pontastacus leptodactylus` (https://www.gbif.org/species/8946295) with 3 synonyms. Keep restricted or widen?
- [x] `Mimulus guttatus` matches with 2:

    - `Mimulus guttatus Fisch.` (https://www.gbif.org/species/7887942) considered synonym of `Erythranthe lutea (L.) G.L.Nesom` (https://www.gbif.org/species/7730307) with a number of synonyms.
    - `Mimulus guttatus Fisch. ex DC.` (https://www.gbif.org/species/6070603) considered synonym of different species `Erythranthe guttata (DC.) G.L.Nesom` (https://www.gbif.org/species/7346102) with a number of synonyms.

    Which one of the two is it? I'll then add that author. Also: keep restricted or widen?

**Comment by qgroom** [comment]
Mimulus guttatus Fisch.  and Mimulus guttatus Fisch. ex DC. are exactly the same thing. Neson is a bit of a splitter so I'm not surprised he has made a new genus, but it is all the samething nevertheless.

**Comment by qgroom** [comment]
For Persicaria wallichii include all the synonyms in the Manual of Alien plants (http://alienplantsbelgium.be/content/rubrivena-polystachya)

**Comment by timadriaens** [comment]
Podarcis siculus is ok, it is also the preferred name according to the [reptile database](http://reptile-database.reptarium.cz/species?genus=Podarcis&species=siculus) that is commonly used as a standard for these beasts

**Comment by peterdesmet** [comment]
@qgroom:

* Mimulus guttatus: might be the same thing, but GBIF backbone considers them differently: as synonyms of different accepted species, so my question remains.
* Persicaria wallichii: we cannot easily cherry pick synonyms. We either keep it with `Persicaria wallichii` (https://www.gbif.org/species/6391908) 988 occ. or extend to `Koenigia polystachya` (https://www.gbif.org/species/8848208) 2013 occ., with all its synonyms. Note that `Rubrivena polystachya` is included in that synonym list.

**Comment by timadriaens** [comment]
I think we need to keep in line with the decisions we made regarding splitting taxa when mapping the Manual of Alien Plants?

**Comment by qgroom** [comment]
I think I understand your question now. The GBIF backbone is wrong.  Mimulus guttatus Fisch.  and Mimulus guttatus Fisch. ex DC. are not synonyms it is the same name just with a different way of writing the author. Neither name is in reality a synonym of Erythranthe lutea (L.) G.L.Nesom. So if you can only use one GBIF name use Mimulus guttatus Fisch. ex DC. (https://www.gbif.org/species/6070603)

**Comment by qgroom** [comment]
widen to Koenigia polystachya

**Comment by timadriaens** [comment]
keep Astacus leptodactylus, take Leuciscus aspius since this seems also the preferred name used by [Fishbase](http://www.fishbase.org/summary/Leuciscus-aspius.html)
