### ISSUE TITLE
Modelling species occurrences

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#15]
Download based on [the modelling species](https://github.com/trias-project/pipeline/blob/642fc791c56750e3a7b25b0ba9efa9d30d5736b4/data/input/modelling_species.tsv) is available at https://doi.org/10.15468/dl.6cljf9

## No occurrences

No occurrences were found in Belgium for:

- [ ] [Carpobrotus edulis](https://www.gbif.org/occurrence/search?taxonKey=3084842&country=BE)
- [ ] [Chelydra serpentina](https://www.gbif.org/occurrence/search?taxonKey=2441905&country=BE)
- [ ] [Elaphe schrenckii](https://www.gbif.org/occurrence/search?taxonKey=2458438&country=BE)
- [ ] [Misgurnus anguillicaudatus](https://www.gbif.org/occurrence/search?taxonKey=2367919&country=BE)
- [ ] [Podarcis siculus](https://www.gbif.org/occurrence/search?taxonKey=9185677&country=BE)

## Under other species name

The following taxa are listed under a different `species name` (i.e. the name of the species GBIF considers the accepted one). `scientific name` is still the original one + only taxa were returned for the name we looked for, as we wanted:

- [x] `Astacus leptodactylus` → `Pontastacus leptodactylus`
- [x] `Mimulus guttatus Fisch. ex DC.` → `Erythranthe guttata`

## Synonyms that are also included

And to know what synonym names were lumped in with the download, check this file (yellow rows): [modelling_species_in_download.xlsx](https://github.com/trias-project/pipeline/files/1741094/modelling_species_in_download.xlsx)

Note: for most (all?) of these, it's very good that they get lumped, because e.g. there are no occurrences in Belgium published under `Neovison vison`: all are published as `Mustela vison` which we wouldn't get if GBIF didn't look for synonyms.

Let me know if you consider all the above acceptable.

**Comment by qgroom** [comment]
I've checked all the plant synonyms included and they are OK.

**Comment by timadriaens** [comment]
the animals are also fine

**Comment by peterdesmet** [comment]
Great! The game is on: who can publish data or observe (and eradicate?) any of the 5 species for which there are no occurrences yet?

**Comment by peterdesmet** [comment]
@qgroom note: "Carpobrotus edulis" (hottentot-fig) is not in the manual of alien plants either... is this normal?

**Comment by timadriaens** [comment]
Carpobrotus was effectively found and eradicated by ANB in Nieuwpoort https://waarnemingen.be/waarneming/view/141236297
This record does not occur in the dataset of waarnemingen.be on gbif because of the date cut-off of 31/12/2016. I expect Filip will add it with the next update of the manual :-)

the others have never been observed in the wild Belgium to my knowledge
