### ISSUE TITLE
Write gbif_download_meta() function

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#2]
Usage:

```R
gbif_download_meta("../data/output/gbif_downloads.csv")
```

The script would:

1. Verify and report errors the input:
    * Can it be found?
    * Is it a csv file?
    * Has a the file a column `gbif_download_key`
3. Use rgbif `occ_download_meta()` to get status information for all downloads in the list
4. Add information for all records in the input file in the columns:
    * gbif_download_created
    * gbif_download_status
    * gbif_download_doi

Example of a response you'll get: http://api.gbif.org/v1/occurrence/download/0000251-150304104939900

**Comment by peterdesmet** [comment]
Note: function should be part of TrIAS R package, not this repository.

**Comment by damianooldoni** [comment]
Done. Function name: update_download_list.R

**Comment by peterdesmet** [comment]
Done in https://github.com/trias-project/trias/pull/2. Closing issue.
