### ISSUE TITLE
Checklist data filters for indicators

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#21]
This issue describes how data will be filtered to get to the data frame described in #17. Some of these will be tackled in the unified checklist.

Filters:

1. Specific checklists
1. Distribution in Belgium
1. occurrenceStatus = present
1. establishmentMeans = introduced
1. Linked to taxonomic backbone. This removes valid taxa, but is necessary for higher classification
1. Remove genera and above (i.e. no species info, is the case for RINSE)
1. Group by accepted taxon?? So we don’t count synonyms of same species.
1. Group by species?? So we don’t count infraspecific taxa

**Comment by damianooldoni** [comment]
About 3rd filter:

> occurrenceStatus = present

@timadriaens and @qgroom : should we filter by `occurrenceStatus = present` as @peterdesmet wrote or should we also consider `occurrenceStatus == doubtful`? For example, in Manual of Alien Plants in Belgium there are 31 taxa with `occurrenceStatus == doubtful` from 28 different species:
 
species | 
--- |
Elatine alsinastrum
Myricaria germanica
Centaurea alba
Pilosella brachiata
Potentilla argentea x inclinata
Prunus fruticans
Linaria simplex
Triticum monococcum
Triticum turgidum
Triticum aestivum
Sporobolus virginicus
Hornungia procumbens
Chenopodium preissmannii
Amsinckia intermedia
Epilobium novae-civitatis
Epilobium interjectum
Picea abies
Pinus sylvestris
Pinus rigida
Pinus pinaster
Galium rubioides
Verbascum interjectum
Hemerocallis lilioasphodelus
Symphoricarpos microphyllus x orbiculatus
Cerastium arvense subsp. arvense x tomentosum
Cherleria laricifolia
Narcissus pseudonarcissus
Narcissus incomparabilis

Or do we go even more relaxed on this constraint by taking into account all taxa with `occurrenceStatus != absent` (not `absent`)? Click [here](http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml) to know more about the meaning of this terms. By the way, up to now I have encountered only taxa with status `present` or `doubtful`.

**Comment by damianooldoni** [comment]
Another consideration about 7th point:
there are 363 synonyms in the checklists Manual of Alien Plants, alien macroinvertebrates and non-native freshwater fishes, whose 353 only in the Manual of the Alien Plants. After filtering only the IAS in Belgium, as explained above, 359 are left. It would be not a problem at all if their `accepted` (and relative  `acceptedKey`) point to taxa not present in these checklists. However, there is a group of 27 taxa whose `acceptedKey` is present as `key`: this means that these species could be count twice. It is a small group, but we should tackle this problem. Probably a specific (little?) function is needed.

**Comment by qgroom** [comment]
Some of your doubtful species are certainly present e.g. _Pinus sylvestris_, _Narcissus pseudonarcissus_, so perhaps it is doubtful that they are naturalized. For _P. sylvestris_ the checklist says it is doubtful only for Brussels. He must mean it is doubtfully naturalized, but cause I'm 100% sure it is present.

_Picea abies, Pinus rigida and Pinus pinaster_ are probably similar cases. They are planted, but it  is doubtful if they are escaping.

For _N. pseudonarcissus_ the checklist is only refering to _Narcissus pseudonarcissus L. subsp. major_ . Not _N. pseudonarcissus_ in general. It is an important distinction as _N. pseudonarcissus_ is a native species, but not this subspecies.

The rest are probably genuinely doubtful species. That is they are doubtfully present.

**Comment by LienReyserhove** [comment]
I would not filter on species for which the `occurrenceStatus = doubtful` and only integrate species for which we are certain they are present to calculate your indicator, this makes your indicator less prone to error. One way to integrate the information on `doubtful` species is to integrate them as potential noise (by integrating them as error bars, just thinking out loud)?

**Comment by peterdesmet** [comment]
@damianooldoni regarding synonyms for which the accepted taxon is ALSO in the checklist, we'll have to take the following approach **in building the unified checklist**:

- Do we accept the accepted taxon suggested by GBIF? => Indicate in `verifiedKey`
- Merge all information with the same `verifiedKey`

Merging that information is no different than merging information for the same (accepted) taxon appearing on two checklists... we just haven't decided yet HOW we will merge that info. 😄

**Comment by damianooldoni** [comment]
Based on developments of unified checklist, we can be sure we group by `verificationKey`. We can then close this issue.
