### ISSUE TITLE
occurrenceStatus filter for checklist data indicator

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/pipeline#26]
This issue will follow the part of issue #21 dedicated to `occurrenceStatus` (point 3). 
Based on what @qgroom wrote on that issue (see https://github.com/trias-project/pipeline/issues/21#issuecomment-381203638) and what he told me today, we decided to change this filter.
I take taxa with `occurrenceStatus` not equal to `ABSENT`, `EXCLUDED` or `EXTINCT`. In R words:
```r
df %>% filter(!status %in% c("ABSENT", "EXCLUDED", "EXTINCT"))
```
@peterdesmet , @LienReyserhove, @timadriaens, something to add about?

**Comment by peterdesmet** [comment]
Looks fine!

**Comment by LienReyserhove** [comment]
I would not filter on species for which the `occurrenceStatus = doubtful` and only integrate species for which we are certain they are present to calculate your indicator, this makes your indicator less prone to error. One way to integrate the information on `doubtful` species is to integrate them as potential noise (by integrating them as error bars, just thinking out loud)?

**Comment by damianooldoni** [comment]
Thanks @LienReyserhove. Your comment relies in fact on the meaning of `DOUBTFUL` and `PRESENT` as described in [GBIF OccurrenceStatus Vocabulary](http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml):

1. `PRESENT`:
> There is at least one well documented record of the taxons presence in the area.

`DOUBTFUL`: 

> The taxon is scored as being present in the area but there is some doubt over the evidence. The doubt may be of different kinds including taxonomic or geographic imprecision in the records.

So, the fact that people assigned sometimes `DOUBTFUL` to `occurrenceStatus` expressing a doubt about naturalization (see @qgroom 's comment https://github.com/trias-project/pipeline/issues/21#issuecomment-381203638) seems to me an incorrect use of `DOUBTFUL`, therefore a mistake.
So, I would filter taxa with `occurrenceStatus` not equal to `ABSENT`, `EXCLUDED`, `EXTINCT` or `DOUBTFUL`. 
In R words:
```r
# not in 
df %>% filter(!status %in% c("ABSENT", "EXCLUDED", "EXTINCT", "DOUBTFUL"))
```
which is equivalent to 
```r
# in
df %>% filter(status %in% c("PRESENT", "COMMON", "RARE", "IRREGULAR"))
```
where `COMMON`, `RARE` and `IRREGULAR` are subclasses of `PRESENT`.

**Comment by damianooldoni** [comment]
@peterdesmet : as discussed on Fri 18th May, could you contact Filip Verloove about the presumably erroneous use of `DOUBTFUL` in The Manual of the Alien Plants of Belgium? Thanks.

**Comment by peterdesmet** [comment]
Assigning this to @LienReyserhove. Not sure this is still a current issue.

**Comment by damianooldoni** [comment]
I agree, @peterdesmet. I think we got an agreement about it., I think. But you are right. Let's wait for final word of @LienReyserhove to close it.

**Comment by damianooldoni** [comment]
@LienReyserhove : if you agree we can close this issue.

**Comment by LienReyserhove** [comment]
sure, you can close it!
