### ISSUE TITLE
establishmentMeans filter for checklist data indicator

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/pipeline#28]
This issue follows point 4 of https://github.com/trias-project/pipeline/issues/21#issue-313765318

Based on discussion with @timadriaens and @qgroom we think to filter based on `establishmentMeans` equal to one of the following terms: `INTRODUCED`, `NATURALISED`, `INVASIVE`, `ASSISTED COLONISATION`. These are the new terms which will be proposed soon and hopefully approved and implemented. Is there a problem on doing that?

**Comment by peterdesmet** [comment]
Looks good. For now, only `INTRODUCED` records will be returned.

**Comment by damianooldoni** [comment]
There is sufficient consensus about this. Issue closed
