### ISSUE TITLE
Structure of data output for checklist indicators

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/pipeline#30]
The data output we get by merging taxonomic information with distribution and description extensions, is "fake" tidy. I wrote *fake* because most of the description is saved by following the [Entity-Value-Model](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) (thanks @stijnvanhoey to find the right word for it) 

For each taxon it appears like the t able here below:

taxonKey | type | description
--- | --- | ---
141264591 | pathway | cbd_2014_pathway:escape_horticulture
141264591 | native range | Southern America (WGSRPD:8)
141264591 | origin | vagrant

I tidy already the pathways by creating two new columns `pathway_level1` and `pathway_level2`:

taxonKey | type | description | pathway_level1 | pathway_level2 
--- | --- | --- | --- | ---
141264591 | pathway | cbd_2014_pathway:escape_horticulture | escape | horticulture
141264591 | native_range | Southern America (WGSRPD:8) | NA | NA
141264591 | origin | vagrant | NA | NA 

However, I am thinking this half-tidy approach can create confusion, because it mixes EAV and not EAV (typical representation) models!

Would it be better to have description data 100% tidy like table here below?

taxonKey | pathway_level1 | pathway_level2 | origin | native_range
--- | --- | --- | --- | ---
141264591 | escape | horticulture | vagrant | Southern America (WGSRPD:8)

I think it would be more understandable. And it would make plot workflow easier I think. What do you think, @stijnvanhoey, @SanderDevisscher and @Yasmine-Verzelen ? If you agree then I will implement it in the workflow and I will export a new test data.frame so that you all can use it asap. Thanks.

**Comment by stijnvanhoey** [comment]
As this will simplify the implementation of #17 #20 (certainly the facets) and require minimal adaptation to #19, fine for me!

**Comment by stijnvanhoey** [comment]
And am I seeing this correctly: the only reason the other duplication is there, is because of the `locality`/`locationID` (apart from you added pathway levels)?
Couldn't we also handle this in the preprocessing such that each `key``is a single row?

**Comment by peterdesmet** [comment]
Before you adapt: note that a taxon can have more than one pathway or native range. How do you express that?

**Comment by SanderDevisscher** [comment]
We could create new seperate datasets with pathways and native ranges with "key" as merge by variable. This would keep things simple to the level needed. for example, need to display pathway related graphs => merge pathway dataset to the base dataset. 

@timadriaens @qgroom 
Is there a need to link pathways to native ranges (is there information/relevance about species getting introduced from a native range via a certain pathway and individuals from a other part of the native range via an other ) ?

**Comment by damianooldoni** [comment]
The approach of @SanderDevisscher follows indeed the third tidy principle:

> Each type of observational unit forms a table.

However, it doesn't result necessarily in one row per `species`: if more pathways exist for some taxa then we will have more rows for the same `species`. But this is not in contrast with tidy representation, at contrary, it is really 100% tidy because `pathway_level1`, `status` etc. are all variables!

Maintaining different  information in different tables with `species` as link  among them is nice, from database point of view, but it makes things a lot more difficult in generic plot functions where a parameter is passed which is used for grouping by. This because a lot of care should be taken in order to distinguish which kind of parameter is given for grouping by, because the column names could not exist in dataframe and the right dataframe should be passed in. Or a join has to be done among dataframes, which is not nice at all.

On the other hand, if just one dataframe is used it results as shown below:

species | genus | ... | pathway_level1 | pathway_level2 | origin | native_range | ... | ...
--- | --- | --- | --- | --- | --- | --- | --- | --- | 
x | g1 | | escape | horticulture | vagrant | Southern America (WGSRPD:8) | | 
x | g1 | | escape | horticulture | vagrant | temperate Asia (WGSRPD:3) | | 

I don't see any problem to count this species on both `native_range` in graph related to `native_range` and, at the same time, using `distinct(species)` for taxonomic based indicators (graphs about how many `species` per year). Moreover, the total number of columns will be not a problem for us: our dataframes are still relatively small.

Small stuff: notice that I replaced `taxonKey`column with `species` in this example because the group by should be done on `species` in order to not count subspecies as two different species (see point 8 of [#21](https://github.com/trias-project/pipeline/issues/21)). Something to not forget while making plots! :+1:

**Comment by peterdesmet** [comment]
@damianooldoni we'll have to see if this approach works, because you multiply the number of records for each combination, e.g. let's say `species A` has `pathway K & L` and `habitat R & S` and `native range X & Y`. That means you would get:

species | pathway | habitat | range
--- | --- | --- | ---
A | K | R | X
A | K | R | Y
A | K | S | X
A | K | S | Y
A | L | R | X
A | L | R | Y
A | L | S | X
A | L | S | Y

**Comment by damianooldoni** [comment]
Yes, @peterdesmet, indeed. This is the most tidy way to create dataframe output for indicators. Number of rows and columns is not a problem, I find. 
Soon a PR with pipeline and new version of data.frame output.

**Comment by damianooldoni** [comment]
Implemented in #32
