### ISSUE TITLE
pathways for subset of policy relevant species

### ISSUE THREAD

**Issue by timadriaens** [trias-project/pipeline#36]
It would be nice to draft the pathway 'indicator' table for the species of the Union list as this links directly to policy on action plans etc.

**Comment by damianooldoni** [comment]
Yes, @timadriaens : this is possible and I will add it as an additional final chapter in the pipeline. I will keep you updated.

**Comment by damianooldoni** [comment]
Done in branch `@pathways`. The pipeline is called: `indicator_pathways.Rmd`. 

@timadriaens, please:

1. open it :open_file_folder: 
2. knit it on your laptop :fork_and_knife:
3. give a look :eyes: 
4. play with it :basketball_man: 
5. let me know :speech_balloon: 

If there are comments, questions or issues not related to this issue, I am more than happy to hear about it, but please make a new issue. 

The challenge to find pathways of :alien: is definitely open!

**Comment by damianooldoni** [comment]
The branch is still to be merged to master. In any  case, issue should be closed.
