### ISSUE TITLE
Write Rmd that explores grid size effect on AOO

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#37]
As discussed with @damianooldoni, he will create a Rmd name `grid_size_effect.Rmd`

## Effect of grid size on AOO (area of occupancy)

* Takeway: AOO for 1km2 < 10km2 < 100km2
* Let's take the most precise 1km grid
* Problem: data collection occurred on larger grid

## Solution 1: downscaling

* Method to resample larger grid data to a smaller grid (many methods)
* Choose simple ensemble to get number of occupied 1KM grids
* Compare with values before

## Solution 2: records have uncertainty

* Lot of data is collected on a larger grid and that information is reported in `coordinateUncertaintyInMeters` which is radius of grid
* Plot coordinate uncertainty circle on grid (figure)
* Ignore all occurrences with uncertainty > 10km
* Randomly assign occurrence points to grids in overlapping area
* New number of occupied 1KM grid
* Compare with values before

## For a select number of species make

Table:

Year | Occ | Coordunc | 100km | 10km | 1km | 1km (downscaling) | 1km (circle based)
--- | --- | --- | --- | --- | --- | --- | ---
2011 | count | mode | % (count) | % (count) | % (count) | % (count) | % (count)
2012 | count | mode | % (count) | % (count) | % (count) | % (count) | % (count)
2013 | count | mode | % (count) | % (count) | % (count) | % (count) | % (count)
2014 | count | mode | % (count) | % (count) | % (count) | % (count) | % (count)
2015 | count | mode | % (count) | % (count) | % (count) | % (count) | % (count)
Totals | total | mode | count | count | count | count | count

Chart:

Comparing % (AOO) of `1km`, `1km (downscaling)`, `1km (circle based)` per year

**Comment by damianooldoni** [comment]
First part and solution 2 done: f18431f9c0b162850bff7d01cbcbe7d190f06fee.
Solution 1 is next step and it will be an adaptation of the downscaling pipeline [here](https://github.com/trias-project/pipeline/blob/occ_indicators_downscaling/src/_occurrence_indicators_downscaling.Rmd) which is the reason why this branch has been created with such name :astonished:

**Comment by damianooldoni** [comment]
Done. The [grid_size_effect.Rmd](https://github.com/trias-project/pipeline/blob/occ_indicators_downscaling/src/grid_size_effect.Rmd) is ready (branch occ_indicators_downscaling). 
A final summary has been added where not only the results are compared (final table you mentioned in the issue) but some graphs have been produced where the differences between solution 1 and 2 are discussed.
Knitted successfully locally (no pushed on repo).

**Comment by peterdesmet** [comment]
Can you knit this as part of the website so we can review the results here on GitHub? If not, I can do it.

**Comment by damianooldoni** [comment]
Could you please do it? In this way we are also sure it works on other laptop(s) and OS. Thanks. 
Knitting will take a while. Please, be patient :sleeping:
