### ISSUE TITLE
GitHub cannot render tsv because of double quotes in scientificName

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/pipeline#6]
On https://github.com/trias-project/pipeline/blob/master/data/output/checklist_taxa.tsv GitHub indicates that it cannot display the file nicely because "Illegal quoting in line 2710.". That line contains:

> Sedum "Autumn Joy" (S. spectabile Boreau x telephium L.)

1. We could set quote=TRUE for the output, but I think that is going to unnecessarily quote everything and might not even resolve the issue. @damianooldoni can you test this on a branch?
2. At some point the file will be to big to display on GitHub anyway.

**Comment by damianooldoni** [comment]
I think this issue is solved. I see that all tsv files in `/data/input/` are rendered correctly.

**Comment by peterdesmet** [comment]
Indeed.
