### ISSUE TITLE
Terminology consistency between pipelines

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/pipeline#9]
At this stage of programming, it should be important to use the same terms to refer to taxon in all pipelines.
Do we use `nubKey` and `taxonomicStatus` as in pipeline _get_taxa_ or `gbif_taxonKey` and `gbif_species_status` as in pipeline _occurrence_?
I would personally opt for `nubKey`  and taxonomicStatus as referred in checklists.
I would also consequently rename the columns of the input file `eu_concern_species.tsv`.

**Comment by damianooldoni** [comment]
I would avoid `gbif_taxonKey` in input/output files and I would opt for `backbone_taxonKey` as we did in `checklist_taxa.tsv`.

**Comment by peterdesmet** [comment]
Agreed.

* Use `backbone_taxonKey` everywhere (although we can still refer to it by the name `nubKey` in writing)
* Use `backbone_taxonomicStatus` everywhere.

So that means updating column headers in `eu_concern_species.csv`.
